#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run-script pack
            - npm run-script dist
            - npm install electron-packager
            - electron-packager ./ SideNoder --platform=win32 --arch=x64
          artifacts:
            - dist/SideNoder*.AppImage
            - dist/SideNoder*.snap