# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run make
        run: |

          sudo npm install
          sudo npm run make all

          mkdir -p /tmp/builds
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/deb/x64/
          mkdir -p /tmp/builds/linux/deb/
          tar -cvf /tmp/builds/linux/deb/SideNoder-linux-x64-deb.tar *.deb
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/rpm/x64/
          mkdir -p /tmp/builds/linux/rpm/
          tar -cvf /tmp/builds/linux/rpm/SideNoder-linux-x64-rpm.tar *.rpm
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/zip/linux/x64/
          mkdir -p /tmp/builds/linux/zip/
          mv *.zip /tmp/builds/linux/zip/

          sudo rm -rf /home/runner/work/quest-sidenoder/quest-sidenoder/out/

          sudo npm run-script pack
          sudo npm run-script dist






      - name: Upload linux Build deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SideNoder-linux-x64-deb
          path: /tmp/builds/linux/deb/
      - name: Upload linux Build rpm Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SideNoder-linux-x64-rpm
          path: /tmp/builds/linux/rpm/
      - name: Upload linux Build zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SideNoder-linux-x64-zip
          path: /tmp/builds/linux/zip/
