# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run make
        run: |

          sudo npm install
          sudo npm run-script pack
          sudo npm run-script dist



          mkdir -p /tmp/builds
          mkdir -p /tmp/builds/AppImage/x64
          mkdir -p /tmp/builds/rpm/x64


          cd /home/runner/work/quest-sidenoder/quest-sidenoder/dist/

          tar -cvf /tmp/builds/AppImage/x64/SideNoder-linux-x64-AppImage.tar SideNoder*.AppImage
          sudo rm -rf /home/runner/work/quest-sidenoder/quest-sidenoder/dist

          sudo npm install electron-packager -g
          electron-packager ./ SideNode --platform=darwin --arch=x64 --out=dist

      - name: electron-packager
        run: |

          sudo rm -rf /home/runner/work/quest-sidenoder/quest-sidenoder/dist/*
          sudo apt install wine64


          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32
          sudo apt install mono-complete

          sudo chown root /home/runner
          sudo chmod 777 -R /home/runner
          sudo chmod 777 -R /usr/local/lib/node_modules

          sudo npm install electron-packager -g  --unsafe-perm=true --allow-root
          sudo electron-packager ./ SideNoder --platform=win32 --arch=x64
          mkdir -p /tmp/builds/win32/x64

          cd /home/runner/work/quest-sidenoder/quest-sidenoder/SideNoder-win32-x64/
          zip -r /tmp/builds/win32/x64/SideNoder-win32-x64.zip *




      - name: Upload linux Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SideNoder-linux-x64-AppImage
          path: /tmp/builds/AppImage/x64/SideNoder-linux-x64-AppImage.tar



      - name: Upload windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SideNoder-win-x64
          path: /tmp/builds/win32/x64/SideNoder-win32-x64.zip
